/**
 * Cloud API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AssetParametersOutput } from './AssetParametersOutput';
import { EnvironmentOutput } from './EnvironmentOutput';
import { HttpFile } from '../http/http';

export class AssetOutput {
    'asset': string;
    'assetVersion': string;
    'id': string;
    'status': string;
    'environment': EnvironmentOutput;
    'currentAssetParameters': AssetParametersOutput;
    'userDefined': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "asset",
            "baseName": "asset",
            "type": "string",
            "format": ""
        },
        {
            "name": "assetVersion",
            "baseName": "asset_version",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "environment",
            "baseName": "environment",
            "type": "EnvironmentOutput",
            "format": ""
        },
        {
            "name": "currentAssetParameters",
            "baseName": "current_asset_parameters",
            "type": "AssetParametersOutput",
            "format": ""
        },
        {
            "name": "userDefined",
            "baseName": "user_defined",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AssetOutput.attributeTypeMap;
    }

    public constructor() {
    }
}

