/**
 * Cloud API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class AssetInput {
    'asset': string;
    'assetVersion': string;
    'assetParameters': any;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "asset",
            "baseName": "asset",
            "type": "string",
            "format": ""
        },
        {
            "name": "assetVersion",
            "baseName": "asset_version",
            "type": "string",
            "format": ""
        },
        {
            "name": "assetParameters",
            "baseName": "asset_parameters",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AssetInput.attributeTypeMap;
    }

    public constructor() {
    }
}

