/**
 * Cloud API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AssetAction } from '../models/AssetAction';
import { HttpFile } from '../http/http';

export class AssetBundle {
    'identifier': string;
    'name': string;
    'description'?: string;
    'types': Array<string>;
    'actions': { [key: string]: AssetAction; };
    'userParameters'?: any;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "identifier",
            "baseName": "identifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "types",
            "baseName": "types",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "actions",
            "baseName": "actions",
            "type": "{ [key: string]: AssetAction; }",
            "format": ""
        },
        {
            "name": "userParameters",
            "baseName": "user_parameters",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AssetBundle.attributeTypeMap;
    }

    public constructor() {
    }
}

