/**
 * Cloud API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AssetOutput } from './AssetOutput';
import { ConnectionStatus } from './ConnectionStatus';
import { OperationOutput } from './OperationOutput';
import { HttpFile } from '../http/http';

export class ConnectionOutput {
    'id': string;
    'incomingConnectionAsset'?: AssetOutput;
    'operations'?: Array<OperationOutput>;
    'outgoingConnectionAsset'?: AssetOutput;
    'status': ConnectionStatus;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "incomingConnectionAsset",
            "baseName": "incoming_connection_asset",
            "type": "AssetOutput",
            "format": ""
        },
        {
            "name": "operations",
            "baseName": "operations",
            "type": "Array<OperationOutput>",
            "format": ""
        },
        {
            "name": "outgoingConnectionAsset",
            "baseName": "outgoing_connection_asset",
            "type": "AssetOutput",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "ConnectionStatus",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ConnectionOutput.attributeTypeMap;
    }

    public constructor() {
    }
}

