/**
 * Cloud API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ActionOutput } from './ActionOutput';
import { OperationActionUpdate } from './OperationActionUpdate';
import { OperationAssetUpdate } from './OperationAssetUpdate';
import { OperationFailure } from './OperationFailure';
import { OperationTerraformRunUpdate } from './OperationTerraformRunUpdate';
import { HttpFile } from '../http/http';

export class Data {
    'error': string;
    'terraformInit': OperationTerraformRunUpdate;
    'terraformPlan'?: OperationTerraformRunUpdate;
    'terraformApply'?: OperationTerraformRunUpdate;
    'terraformPlanFailures'?: string;
    'terraformApplyFailures'?: string;
    'actionOutput': ActionOutput;
    'actionErrors'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "error",
            "baseName": "error",
            "type": "string",
            "format": ""
        },
        {
            "name": "terraformInit",
            "baseName": "terraform_init",
            "type": "OperationTerraformRunUpdate",
            "format": ""
        },
        {
            "name": "terraformPlan",
            "baseName": "terraform_plan",
            "type": "OperationTerraformRunUpdate",
            "format": ""
        },
        {
            "name": "terraformApply",
            "baseName": "terraform_apply",
            "type": "OperationTerraformRunUpdate",
            "format": ""
        },
        {
            "name": "terraformPlanFailures",
            "baseName": "terraform_plan_failures",
            "type": "string",
            "format": ""
        },
        {
            "name": "terraformApplyFailures",
            "baseName": "terraform_apply_failures",
            "type": "string",
            "format": ""
        },
        {
            "name": "actionOutput",
            "baseName": "action_output",
            "type": "ActionOutput",
            "format": ""
        },
        {
            "name": "actionErrors",
            "baseName": "action_errors",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Data.attributeTypeMap;
    }

    public constructor() {
    }
}

