/**
 * Cloud API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class OrganizationOutput {
    'name': string;
    'baaStatus': string;
    'awsOu'?: string;
    'contactDetails': any;
    'id': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "baaStatus",
            "baseName": "baa_status",
            "type": "string",
            "format": ""
        },
        {
            "name": "awsOu",
            "baseName": "aws_ou",
            "type": "string",
            "format": ""
        },
        {
            "name": "contactDetails",
            "baseName": "contact_details",
            "type": "any",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        }    ];

    static getAttributeTypeMap() {
        return OrganizationOutput.attributeTypeMap;
    }

    public constructor() {
    }
}

