# coding: utf-8

"""
    Cloud API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import cloud_api_client
from cloud_api_client.model.operation_update import OperationUpdate
from cloud_api_client import configuration


class TestOperationUpdate(unittest.TestCase):
    """OperationUpdate unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
