/*
Cloud API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloud_api_client

import (
	"encoding/json"
	"fmt"
)

// Structure struct for Structure
type Structure struct {
	Array *Array
	string *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *Structure) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into Array
	err = json.Unmarshal(data, &dst.Array);
	if err == nil {
		jsonArray, _ := json.Marshal(dst.Array)
		if string(jsonArray) == "{}" { // empty struct
			dst.Array = nil
		} else {
			return nil // data stored in dst.Array, return on the first match
		}
	} else {
		dst.Array = nil
	}

	// try to unmarshal JSON data into string
	err = json.Unmarshal(data, &dst.string);
	if err == nil {
		jsonstring, _ := json.Marshal(dst.string)
		if string(jsonstring) == "{}" { // empty struct
			dst.string = nil
		} else {
			return nil // data stored in dst.string, return on the first match
		}
	} else {
		dst.string = nil
	}

	return fmt.Errorf("Data failed to match schemas in anyOf(Structure)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *Structure) MarshalJSON() ([]byte, error) {
	if src.Array != nil {
		return json.Marshal(&src.Array)
	}

	if src.string != nil {
		return json.Marshal(&src.string)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableStructure struct {
	value *Structure
	isSet bool
}

func (v NullableStructure) Get() *Structure {
	return v.value
}

func (v *NullableStructure) Set(val *Structure) {
	v.value = val
	v.isSet = true
}

func (v NullableStructure) IsSet() bool {
	return v.isSet
}

func (v *NullableStructure) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStructure(val *Structure) *NullableStructure {
	return &NullableStructure{value: val, isSet: true}
}

func (v NullableStructure) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStructure) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


