/*
Cloud API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloud_api_client

import (
	"encoding/json"
)

// OperationAssetUpdate struct for OperationAssetUpdate
type OperationAssetUpdate struct {
	TerraformInit *OperationTerraformRunUpdate `json:"terraform_init,omitempty"`
	TerraformPlan *OperationTerraformRunUpdate `json:"terraform_plan,omitempty"`
	TerraformApply *OperationTerraformRunUpdate `json:"terraform_apply,omitempty"`
}

// NewOperationAssetUpdate instantiates a new OperationAssetUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOperationAssetUpdate() *OperationAssetUpdate {
	this := OperationAssetUpdate{}
	return &this
}

// NewOperationAssetUpdateWithDefaults instantiates a new OperationAssetUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOperationAssetUpdateWithDefaults() *OperationAssetUpdate {
	this := OperationAssetUpdate{}
	return &this
}

// GetTerraformInit returns the TerraformInit field value if set, zero value otherwise.
func (o *OperationAssetUpdate) GetTerraformInit() OperationTerraformRunUpdate {
	if o == nil || o.TerraformInit == nil {
		var ret OperationTerraformRunUpdate
		return ret
	}
	return *o.TerraformInit
}

// GetTerraformInitOk returns a tuple with the TerraformInit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OperationAssetUpdate) GetTerraformInitOk() (*OperationTerraformRunUpdate, bool) {
	if o == nil || o.TerraformInit == nil {
		return nil, false
	}
	return o.TerraformInit, true
}

// HasTerraformInit returns a boolean if a field has been set.
func (o *OperationAssetUpdate) HasTerraformInit() bool {
	if o != nil && o.TerraformInit != nil {
		return true
	}

	return false
}

// SetTerraformInit gets a reference to the given OperationTerraformRunUpdate and assigns it to the TerraformInit field.
func (o *OperationAssetUpdate) SetTerraformInit(v OperationTerraformRunUpdate) {
	o.TerraformInit = &v
}

// GetTerraformPlan returns the TerraformPlan field value if set, zero value otherwise.
func (o *OperationAssetUpdate) GetTerraformPlan() OperationTerraformRunUpdate {
	if o == nil || o.TerraformPlan == nil {
		var ret OperationTerraformRunUpdate
		return ret
	}
	return *o.TerraformPlan
}

// GetTerraformPlanOk returns a tuple with the TerraformPlan field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OperationAssetUpdate) GetTerraformPlanOk() (*OperationTerraformRunUpdate, bool) {
	if o == nil || o.TerraformPlan == nil {
		return nil, false
	}
	return o.TerraformPlan, true
}

// HasTerraformPlan returns a boolean if a field has been set.
func (o *OperationAssetUpdate) HasTerraformPlan() bool {
	if o != nil && o.TerraformPlan != nil {
		return true
	}

	return false
}

// SetTerraformPlan gets a reference to the given OperationTerraformRunUpdate and assigns it to the TerraformPlan field.
func (o *OperationAssetUpdate) SetTerraformPlan(v OperationTerraformRunUpdate) {
	o.TerraformPlan = &v
}

// GetTerraformApply returns the TerraformApply field value if set, zero value otherwise.
func (o *OperationAssetUpdate) GetTerraformApply() OperationTerraformRunUpdate {
	if o == nil || o.TerraformApply == nil {
		var ret OperationTerraformRunUpdate
		return ret
	}
	return *o.TerraformApply
}

// GetTerraformApplyOk returns a tuple with the TerraformApply field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OperationAssetUpdate) GetTerraformApplyOk() (*OperationTerraformRunUpdate, bool) {
	if o == nil || o.TerraformApply == nil {
		return nil, false
	}
	return o.TerraformApply, true
}

// HasTerraformApply returns a boolean if a field has been set.
func (o *OperationAssetUpdate) HasTerraformApply() bool {
	if o != nil && o.TerraformApply != nil {
		return true
	}

	return false
}

// SetTerraformApply gets a reference to the given OperationTerraformRunUpdate and assigns it to the TerraformApply field.
func (o *OperationAssetUpdate) SetTerraformApply(v OperationTerraformRunUpdate) {
	o.TerraformApply = &v
}

func (o OperationAssetUpdate) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.TerraformInit != nil {
		toSerialize["terraform_init"] = o.TerraformInit
	}
	if o.TerraformPlan != nil {
		toSerialize["terraform_plan"] = o.TerraformPlan
	}
	if o.TerraformApply != nil {
		toSerialize["terraform_apply"] = o.TerraformApply
	}
	return json.Marshal(toSerialize)
}

type NullableOperationAssetUpdate struct {
	value *OperationAssetUpdate
	isSet bool
}

func (v NullableOperationAssetUpdate) Get() *OperationAssetUpdate {
	return v.value
}

func (v *NullableOperationAssetUpdate) Set(val *OperationAssetUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableOperationAssetUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableOperationAssetUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOperationAssetUpdate(val *OperationAssetUpdate) *NullableOperationAssetUpdate {
	return &NullableOperationAssetUpdate{value: val, isSet: true}
}

func (v NullableOperationAssetUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOperationAssetUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


