/*
Cloud API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloud_api_client

import (
	"encoding/json"
)

// OperationActionUpdate struct for OperationActionUpdate
type OperationActionUpdate struct {
	ActionOutput ActionOutput `json:"action_output"`
	ActionErrors *string `json:"action_errors,omitempty"`
}

// NewOperationActionUpdate instantiates a new OperationActionUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOperationActionUpdate(actionOutput ActionOutput) *OperationActionUpdate {
	this := OperationActionUpdate{}
	this.ActionOutput = actionOutput
	return &this
}

// NewOperationActionUpdateWithDefaults instantiates a new OperationActionUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOperationActionUpdateWithDefaults() *OperationActionUpdate {
	this := OperationActionUpdate{}
	return &this
}

// GetActionOutput returns the ActionOutput field value
func (o *OperationActionUpdate) GetActionOutput() ActionOutput {
	if o == nil {
		var ret ActionOutput
		return ret
	}

	return o.ActionOutput
}

// GetActionOutputOk returns a tuple with the ActionOutput field value
// and a boolean to check if the value has been set.
func (o *OperationActionUpdate) GetActionOutputOk() (*ActionOutput, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ActionOutput, true
}

// SetActionOutput sets field value
func (o *OperationActionUpdate) SetActionOutput(v ActionOutput) {
	o.ActionOutput = v
}

// GetActionErrors returns the ActionErrors field value if set, zero value otherwise.
func (o *OperationActionUpdate) GetActionErrors() string {
	if o == nil || o.ActionErrors == nil {
		var ret string
		return ret
	}
	return *o.ActionErrors
}

// GetActionErrorsOk returns a tuple with the ActionErrors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OperationActionUpdate) GetActionErrorsOk() (*string, bool) {
	if o == nil || o.ActionErrors == nil {
		return nil, false
	}
	return o.ActionErrors, true
}

// HasActionErrors returns a boolean if a field has been set.
func (o *OperationActionUpdate) HasActionErrors() bool {
	if o != nil && o.ActionErrors != nil {
		return true
	}

	return false
}

// SetActionErrors gets a reference to the given string and assigns it to the ActionErrors field.
func (o *OperationActionUpdate) SetActionErrors(v string) {
	o.ActionErrors = &v
}

func (o OperationActionUpdate) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["action_output"] = o.ActionOutput
	}
	if o.ActionErrors != nil {
		toSerialize["action_errors"] = o.ActionErrors
	}
	return json.Marshal(toSerialize)
}

type NullableOperationActionUpdate struct {
	value *OperationActionUpdate
	isSet bool
}

func (v NullableOperationActionUpdate) Get() *OperationActionUpdate {
	return v.value
}

func (v *NullableOperationActionUpdate) Set(val *OperationActionUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableOperationActionUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableOperationActionUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOperationActionUpdate(val *OperationActionUpdate) *NullableOperationActionUpdate {
	return &NullableOperationActionUpdate{value: val, isSet: true}
}

func (v NullableOperationActionUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOperationActionUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


