/*
Cloud API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloud_api_client

import (
	"encoding/json"
)

// AssetAction struct for AssetAction
type AssetAction struct {
	Name string `json:"name"`
	Description *string `json:"description,omitempty"`
	UserParameters interface{} `json:"user_parameters,omitempty"`
}

// NewAssetAction instantiates a new AssetAction object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssetAction(name string) *AssetAction {
	this := AssetAction{}
	this.Name = name
	return &this
}

// NewAssetActionWithDefaults instantiates a new AssetAction object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssetActionWithDefaults() *AssetAction {
	this := AssetAction{}
	return &this
}

// GetName returns the Name field value
func (o *AssetAction) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AssetAction) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AssetAction) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *AssetAction) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetAction) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *AssetAction) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *AssetAction) SetDescription(v string) {
	o.Description = &v
}

// GetUserParameters returns the UserParameters field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AssetAction) GetUserParameters() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.UserParameters
}

// GetUserParametersOk returns a tuple with the UserParameters field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AssetAction) GetUserParametersOk() (*interface{}, bool) {
	if o == nil || o.UserParameters == nil {
		return nil, false
	}
	return &o.UserParameters, true
}

// HasUserParameters returns a boolean if a field has been set.
func (o *AssetAction) HasUserParameters() bool {
	if o != nil && o.UserParameters != nil {
		return true
	}

	return false
}

// SetUserParameters gets a reference to the given interface{} and assigns it to the UserParameters field.
func (o *AssetAction) SetUserParameters(v interface{}) {
	o.UserParameters = v
}

func (o AssetAction) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.UserParameters != nil {
		toSerialize["user_parameters"] = o.UserParameters
	}
	return json.Marshal(toSerialize)
}

type NullableAssetAction struct {
	value *AssetAction
	isSet bool
}

func (v NullableAssetAction) Get() *AssetAction {
	return v.value
}

func (v *NullableAssetAction) Set(val *AssetAction) {
	v.value = val
	v.isSet = true
}

func (v NullableAssetAction) IsSet() bool {
	return v.isSet
}

func (v *NullableAssetAction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssetAction(val *AssetAction) *NullableAssetAction {
	return &NullableAssetAction{value: val, isSet: true}
}

func (v NullableAssetAction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssetAction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


