/*
Cloud API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloud_api_client

import (
	"encoding/json"
)

// AssetInput struct for AssetInput
type AssetInput struct {
	Asset string `json:"asset"`
	AssetVersion string `json:"asset_version"`
	AssetVariables map[string]interface{} `json:"asset_variables"`
}

// NewAssetInput instantiates a new AssetInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssetInput(asset string, assetVersion string, assetVariables map[string]interface{}) *AssetInput {
	this := AssetInput{}
	this.Asset = asset
	this.AssetVersion = assetVersion
	this.AssetVariables = assetVariables
	return &this
}

// NewAssetInputWithDefaults instantiates a new AssetInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssetInputWithDefaults() *AssetInput {
	this := AssetInput{}
	return &this
}

// GetAsset returns the Asset field value
func (o *AssetInput) GetAsset() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Asset
}

// GetAssetOk returns a tuple with the Asset field value
// and a boolean to check if the value has been set.
func (o *AssetInput) GetAssetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Asset, true
}

// SetAsset sets field value
func (o *AssetInput) SetAsset(v string) {
	o.Asset = v
}

// GetAssetVersion returns the AssetVersion field value
func (o *AssetInput) GetAssetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AssetVersion
}

// GetAssetVersionOk returns a tuple with the AssetVersion field value
// and a boolean to check if the value has been set.
func (o *AssetInput) GetAssetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AssetVersion, true
}

// SetAssetVersion sets field value
func (o *AssetInput) SetAssetVersion(v string) {
	o.AssetVersion = v
}

// GetAssetVariables returns the AssetVariables field value
func (o *AssetInput) GetAssetVariables() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.AssetVariables
}

// GetAssetVariablesOk returns a tuple with the AssetVariables field value
// and a boolean to check if the value has been set.
func (o *AssetInput) GetAssetVariablesOk() (map[string]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.AssetVariables, true
}

// SetAssetVariables sets field value
func (o *AssetInput) SetAssetVariables(v map[string]interface{}) {
	o.AssetVariables = v
}

func (o AssetInput) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["asset"] = o.Asset
	}
	if true {
		toSerialize["asset_version"] = o.AssetVersion
	}
	if true {
		toSerialize["asset_variables"] = o.AssetVariables
	}
	return json.Marshal(toSerialize)
}

type NullableAssetInput struct {
	value *AssetInput
	isSet bool
}

func (v NullableAssetInput) Get() *AssetInput {
	return v.value
}

func (v *NullableAssetInput) Set(val *AssetInput) {
	v.value = val
	v.isSet = true
}

func (v NullableAssetInput) IsSet() bool {
	return v.isSet
}

func (v *NullableAssetInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssetInput(val *AssetInput) *NullableAssetInput {
	return &NullableAssetInput{value: val, isSet: true}
}

func (v NullableAssetInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssetInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


