/*
Cloud API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloud_api_client

import (
	"encoding/json"
)

// OrganizationOutput struct for OrganizationOutput
type OrganizationOutput struct {
	Name string `json:"name"`
	BaaStatus string `json:"baa_status"`
	AwsOu string `json:"aws_ou"`
	ContactDetails map[string]interface{} `json:"contact_details"`
	Id string `json:"id"`
}

// NewOrganizationOutput instantiates a new OrganizationOutput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganizationOutput(name string, baaStatus string, awsOu string, contactDetails map[string]interface{}, id string) *OrganizationOutput {
	this := OrganizationOutput{}
	this.Name = name
	this.BaaStatus = baaStatus
	this.AwsOu = awsOu
	this.ContactDetails = contactDetails
	this.Id = id
	return &this
}

// NewOrganizationOutputWithDefaults instantiates a new OrganizationOutput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizationOutputWithDefaults() *OrganizationOutput {
	this := OrganizationOutput{}
	return &this
}

// GetName returns the Name field value
func (o *OrganizationOutput) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *OrganizationOutput) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *OrganizationOutput) SetName(v string) {
	o.Name = v
}

// GetBaaStatus returns the BaaStatus field value
func (o *OrganizationOutput) GetBaaStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BaaStatus
}

// GetBaaStatusOk returns a tuple with the BaaStatus field value
// and a boolean to check if the value has been set.
func (o *OrganizationOutput) GetBaaStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BaaStatus, true
}

// SetBaaStatus sets field value
func (o *OrganizationOutput) SetBaaStatus(v string) {
	o.BaaStatus = v
}

// GetAwsOu returns the AwsOu field value
func (o *OrganizationOutput) GetAwsOu() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AwsOu
}

// GetAwsOuOk returns a tuple with the AwsOu field value
// and a boolean to check if the value has been set.
func (o *OrganizationOutput) GetAwsOuOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AwsOu, true
}

// SetAwsOu sets field value
func (o *OrganizationOutput) SetAwsOu(v string) {
	o.AwsOu = v
}

// GetContactDetails returns the ContactDetails field value
func (o *OrganizationOutput) GetContactDetails() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.ContactDetails
}

// GetContactDetailsOk returns a tuple with the ContactDetails field value
// and a boolean to check if the value has been set.
func (o *OrganizationOutput) GetContactDetailsOk() (map[string]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.ContactDetails, true
}

// SetContactDetails sets field value
func (o *OrganizationOutput) SetContactDetails(v map[string]interface{}) {
	o.ContactDetails = v
}

// GetId returns the Id field value
func (o *OrganizationOutput) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *OrganizationOutput) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *OrganizationOutput) SetId(v string) {
	o.Id = v
}

func (o OrganizationOutput) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["baa_status"] = o.BaaStatus
	}
	if true {
		toSerialize["aws_ou"] = o.AwsOu
	}
	if true {
		toSerialize["contact_details"] = o.ContactDetails
	}
	if true {
		toSerialize["id"] = o.Id
	}
	return json.Marshal(toSerialize)
}

type NullableOrganizationOutput struct {
	value *OrganizationOutput
	isSet bool
}

func (v NullableOrganizationOutput) Get() *OrganizationOutput {
	return v.value
}

func (v *NullableOrganizationOutput) Set(val *OrganizationOutput) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganizationOutput) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganizationOutput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganizationOutput(val *OrganizationOutput) *NullableOrganizationOutput {
	return &NullableOrganizationOutput{value: val, isSet: true}
}

func (v NullableOrganizationOutput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganizationOutput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


