/*
Cloud API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloud_api_client

import (
	"encoding/json"
)

// OperationAssetUpdate struct for OperationAssetUpdate
type OperationAssetUpdate struct {
	TerraformStdout []map[string]interface{} `json:"terraform_stdout"`
	TerraformStdin []map[string]interface{} `json:"terraform_stdin"`
	TerraformReturnCode int32 `json:"terraform_return_code"`
}

// NewOperationAssetUpdate instantiates a new OperationAssetUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOperationAssetUpdate(terraformStdout []map[string]interface{}, terraformStdin []map[string]interface{}, terraformReturnCode int32) *OperationAssetUpdate {
	this := OperationAssetUpdate{}
	this.TerraformStdout = terraformStdout
	this.TerraformStdin = terraformStdin
	this.TerraformReturnCode = terraformReturnCode
	return &this
}

// NewOperationAssetUpdateWithDefaults instantiates a new OperationAssetUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOperationAssetUpdateWithDefaults() *OperationAssetUpdate {
	this := OperationAssetUpdate{}
	return &this
}

// GetTerraformStdout returns the TerraformStdout field value
func (o *OperationAssetUpdate) GetTerraformStdout() []map[string]interface{} {
	if o == nil {
		var ret []map[string]interface{}
		return ret
	}

	return o.TerraformStdout
}

// GetTerraformStdoutOk returns a tuple with the TerraformStdout field value
// and a boolean to check if the value has been set.
func (o *OperationAssetUpdate) GetTerraformStdoutOk() ([]map[string]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.TerraformStdout, true
}

// SetTerraformStdout sets field value
func (o *OperationAssetUpdate) SetTerraformStdout(v []map[string]interface{}) {
	o.TerraformStdout = v
}

// GetTerraformStdin returns the TerraformStdin field value
func (o *OperationAssetUpdate) GetTerraformStdin() []map[string]interface{} {
	if o == nil {
		var ret []map[string]interface{}
		return ret
	}

	return o.TerraformStdin
}

// GetTerraformStdinOk returns a tuple with the TerraformStdin field value
// and a boolean to check if the value has been set.
func (o *OperationAssetUpdate) GetTerraformStdinOk() ([]map[string]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.TerraformStdin, true
}

// SetTerraformStdin sets field value
func (o *OperationAssetUpdate) SetTerraformStdin(v []map[string]interface{}) {
	o.TerraformStdin = v
}

// GetTerraformReturnCode returns the TerraformReturnCode field value
func (o *OperationAssetUpdate) GetTerraformReturnCode() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TerraformReturnCode
}

// GetTerraformReturnCodeOk returns a tuple with the TerraformReturnCode field value
// and a boolean to check if the value has been set.
func (o *OperationAssetUpdate) GetTerraformReturnCodeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TerraformReturnCode, true
}

// SetTerraformReturnCode sets field value
func (o *OperationAssetUpdate) SetTerraformReturnCode(v int32) {
	o.TerraformReturnCode = v
}

func (o OperationAssetUpdate) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["terraform_stdout"] = o.TerraformStdout
	}
	if true {
		toSerialize["terraform_stdin"] = o.TerraformStdin
	}
	if true {
		toSerialize["terraform_return_code"] = o.TerraformReturnCode
	}
	return json.Marshal(toSerialize)
}

type NullableOperationAssetUpdate struct {
	value *OperationAssetUpdate
	isSet bool
}

func (v NullableOperationAssetUpdate) Get() *OperationAssetUpdate {
	return v.value
}

func (v *NullableOperationAssetUpdate) Set(val *OperationAssetUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableOperationAssetUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableOperationAssetUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOperationAssetUpdate(val *OperationAssetUpdate) *NullableOperationAssetUpdate {
	return &NullableOperationAssetUpdate{value: val, isSet: true}
}

func (v NullableOperationAssetUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOperationAssetUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


