=begin
#Cloud API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.1.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for CloudApiClient::ConnectionStatus
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe CloudApiClient::ConnectionStatus do
  let(:instance) { CloudApiClient::ConnectionStatus.new }

  describe 'test an instance of ConnectionStatus' do
    it 'should create an instance of ConnectionStatus' do
      expect(instance).to be_instance_of(CloudApiClient::ConnectionStatus)
    end
  end
end
