=begin
#Cloud API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for CloudApiClient::OperationActionUpdate
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe CloudApiClient::OperationActionUpdate do
  let(:instance) { CloudApiClient::OperationActionUpdate.new }

  describe 'test an instance of OperationActionUpdate' do
    it 'should create an instance of OperationActionUpdate' do
      expect(instance).to be_instance_of(CloudApiClient::OperationActionUpdate)
    end
  end
  describe 'test attribute "action_output"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "action_errors"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
