from cloud_api_client.paths.api_v1_organizations_organization_id_environments_environment_id_assets_asset_id_connections_connection_id.get import ApiForget
from cloud_api_client.paths.api_v1_organizations_organization_id_environments_environment_id_assets_asset_id_connections_connection_id.delete import ApiFordelete


class ApiV1OrganizationsOrganizationIdEnvironmentsEnvironmentIdAssetsAssetIdConnectionsConnectionId(
    ApiForget,
    ApiFordelete,
):
    pass
