from cloud_api_client.paths.api_v1_organizations_organization_id_environments_environment_id_assets_asset_id_action_action_id.get import ApiForget


class ApiV1OrganizationsOrganizationIdEnvironmentsEnvironmentIdAssetsAssetIdActionActionId(
    ApiForget,
):
    pass
