=begin
#Cloud API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.1.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for CloudApiClient::ActionsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ActionsApi' do
  before do
    # run before each test
    @api_instance = CloudApiClient::ActionsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ActionsApi' do
    it 'should create an instance of ActionsApi' do
      expect(@api_instance).to be_instance_of(CloudApiClient::ActionsApi)
    end
  end

  # unit tests for action_create
  # Action Create
  # @param asset_id 
  # @param environment_id 
  # @param organization_id 
  # @param action_request 
  # @param [Hash] opts the optional parameters
  # @return [ActionResponse]
  describe 'action_create test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for action_get
  # Action Get
  # @param asset_id 
  # @param environment_id 
  # @param action_id 
  # @param organization_id 
  # @param [Hash] opts the optional parameters
  # @return [ActionResponse]
  describe 'action_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
