=begin
#Cloud API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.1.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for CloudApiClient::AssetsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AssetsApi' do
  before do
    # run before each test
    @api_instance = CloudApiClient::AssetsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AssetsApi' do
    it 'should create an instance of AssetsApi' do
      expect(@api_instance).to be_instance_of(CloudApiClient::AssetsApi)
    end
  end

  # unit tests for asset_create
  # Asset Create
  # @param environment_id 
  # @param organization_id 
  # @param asset_input 
  # @param [Hash] opts the optional parameters
  # @return [AssetOutput]
  describe 'asset_create test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for asset_delete
  # Asset Delete
  # @param asset_id 
  # @param environment_id 
  # @param organization_id 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'asset_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for asset_get
  # Asset Get
  # @param asset_id 
  # @param environment_id 
  # @param organization_id 
  # @param [Hash] opts the optional parameters
  # @return [AssetOutput]
  describe 'asset_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for asset_update
  # Asset Update
  # @param asset_id 
  # @param environment_id 
  # @param organization_id 
  # @param asset_input 
  # @param [Hash] opts the optional parameters
  # @return [AssetOutput]
  describe 'asset_update test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
