=begin
#Cloud API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.1

=end

require 'spec_helper'
require 'json'

# Unit tests for CloudApiClient::ConnectionsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ConnectionsApi' do
  before do
    # run before each test
    @api_instance = CloudApiClient::ConnectionsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ConnectionsApi' do
    it 'should create an instance of ConnectionsApi' do
      expect(@api_instance).to be_instance_of(CloudApiClient::ConnectionsApi)
    end
  end

  # unit tests for connection_create
  # Connection Create
  # @param asset_id 
  # @param environment_id 
  # @param organization_id 
  # @param connection_input 
  # @param [Hash] opts the optional parameters
  # @return [ConnectionOutput]
  describe 'connection_create test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for connection_delete
  # Connection Delete
  # @param asset_id 
  # @param connection_id 
  # @param environment_id 
  # @param organization_id 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'connection_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for connection_get
  # Connection Get
  # @param asset_id 
  # @param environment_id 
  # @param connection_id 
  # @param organization_id 
  # @param [Hash] opts the optional parameters
  # @return [ConnectionOutput]
  describe 'connection_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
