=begin
#Cloud API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.1.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for CloudApiClient::UtilitiesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'UtilitiesApi' do
  before do
    # run before each test
    @api_instance = CloudApiClient::UtilitiesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UtilitiesApi' do
    it 'should create an instance of UtilitiesApi' do
      expect(@api_instance).to be_instance_of(CloudApiClient::UtilitiesApi)
    end
  end

  # unit tests for get_ping
  # Get Ping
  # @param [Hash] opts the optional parameters
  # @return [TextResponse]
  describe 'get_ping test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_user
  # Get User
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'get_user test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_user_role
  # Get User Role
  # @param organization_id 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'get_user_role test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
