import typing_extensions

from cloud_api_client.paths import PathValues
from cloud_api_client.apis.paths.api_v1_organizations_organization_id_environments_environment_id_assets_asset_id import ApiV1OrganizationsOrganizationIdEnvironmentsEnvironmentIdAssetsAssetId
from cloud_api_client.apis.paths.api_v1_organizations_organization_id_environments_environment_id_assets import ApiV1OrganizationsOrganizationIdEnvironmentsEnvironmentIdAssets
from cloud_api_client.apis.paths.api_v1_organizations_organization_id_environments_environment_id_assets_asset_id_action import ApiV1OrganizationsOrganizationIdEnvironmentsEnvironmentIdAssetsAssetIdAction
from cloud_api_client.apis.paths.api_v1_organizations_organization_id_environments_environment_id_assets_asset_id_action_action_id import ApiV1OrganizationsOrganizationIdEnvironmentsEnvironmentIdAssetsAssetIdActionActionId
from cloud_api_client.apis.paths.api_v1_organizations_organization_id_environments_environment_id_asset_bundles import ApiV1OrganizationsOrganizationIdEnvironmentsEnvironmentIdAssetBundles
from cloud_api_client.apis.paths.api_v1_organizations_organization_id_environments_environment_id_connections import ApiV1OrganizationsOrganizationIdEnvironmentsEnvironmentIdConnections
from cloud_api_client.apis.paths.api_v1_organizations_organization_id_environments_environment_id import ApiV1OrganizationsOrganizationIdEnvironmentsEnvironmentId
from cloud_api_client.apis.paths.api_v1_organizations_organization_id_environments import ApiV1OrganizationsOrganizationIdEnvironments
from cloud_api_client.apis.paths.api_v1_worker_health_check import ApiV1WorkerHealthCheck
from cloud_api_client.apis.paths.api_v1_organizations_organization_id_environments_environment_id_assets_asset_id_connections_ import ApiV1OrganizationsOrganizationIdEnvironmentsEnvironmentIdAssetsAssetIdConnections
from cloud_api_client.apis.paths.api_v1_organizations_organization_id_environments_environment_id_assets_asset_id_connections_connection_id import ApiV1OrganizationsOrganizationIdEnvironmentsEnvironmentIdAssetsAssetIdConnectionsConnectionId
from cloud_api_client.apis.paths.api_v1_organizations_organization_id_operations_operation_id import ApiV1OrganizationsOrganizationIdOperationsOperationId
from cloud_api_client.apis.paths.api_v1_operations_operation_id import ApiV1OperationsOperationId
from cloud_api_client.apis.paths.api_v1_organizations_organization_id import ApiV1OrganizationsOrganizationId
from cloud_api_client.apis.paths.api_v1_organizations_ import ApiV1Organizations
from cloud_api_client.apis.paths.api_v1_organizations_organization_id_operations_ import ApiV1OrganizationsOrganizationIdOperations
from cloud_api_client.apis.paths.api_v1_system_health_check import ApiV1SystemHealthCheck
from cloud_api_client.apis.paths.api_v1_debug_user_auth import ApiV1DebugUserAuth
from cloud_api_client.apis.paths.api_v1_debug_user_role_middleware_check import ApiV1DebugUserRoleMiddlewareCheck

PathToApi = typing_extensions.TypedDict(
    'PathToApi',
    {
        PathValues.API_V1_ORGANIZATIONS_ORGANIZATION_ID_ENVIRONMENTS_ENVIRONMENT_ID_ASSETS_ASSET_ID: ApiV1OrganizationsOrganizationIdEnvironmentsEnvironmentIdAssetsAssetId,
        PathValues.API_V1_ORGANIZATIONS_ORGANIZATION_ID_ENVIRONMENTS_ENVIRONMENT_ID_ASSETS: ApiV1OrganizationsOrganizationIdEnvironmentsEnvironmentIdAssets,
        PathValues.API_V1_ORGANIZATIONS_ORGANIZATION_ID_ENVIRONMENTS_ENVIRONMENT_ID_ASSETS_ASSET_ID_ACTION: ApiV1OrganizationsOrganizationIdEnvironmentsEnvironmentIdAssetsAssetIdAction,
        PathValues.API_V1_ORGANIZATIONS_ORGANIZATION_ID_ENVIRONMENTS_ENVIRONMENT_ID_ASSETS_ASSET_ID_ACTION_ACTION_ID: ApiV1OrganizationsOrganizationIdEnvironmentsEnvironmentIdAssetsAssetIdActionActionId,
        PathValues.API_V1_ORGANIZATIONS_ORGANIZATION_ID_ENVIRONMENTS_ENVIRONMENT_ID_ASSET_BUNDLES: ApiV1OrganizationsOrganizationIdEnvironmentsEnvironmentIdAssetBundles,
        PathValues.API_V1_ORGANIZATIONS_ORGANIZATION_ID_ENVIRONMENTS_ENVIRONMENT_ID_CONNECTIONS: ApiV1OrganizationsOrganizationIdEnvironmentsEnvironmentIdConnections,
        PathValues.API_V1_ORGANIZATIONS_ORGANIZATION_ID_ENVIRONMENTS_ENVIRONMENT_ID: ApiV1OrganizationsOrganizationIdEnvironmentsEnvironmentId,
        PathValues.API_V1_ORGANIZATIONS_ORGANIZATION_ID_ENVIRONMENTS: ApiV1OrganizationsOrganizationIdEnvironments,
        PathValues.API_V1_WORKER_HEALTHCHECK: ApiV1WorkerHealthCheck,
        PathValues.API_V1_ORGANIZATIONS_ORGANIZATION_ID_ENVIRONMENTS_ENVIRONMENT_ID_ASSETS_ASSET_ID_CONNECTIONS_: ApiV1OrganizationsOrganizationIdEnvironmentsEnvironmentIdAssetsAssetIdConnections,
        PathValues.API_V1_ORGANIZATIONS_ORGANIZATION_ID_ENVIRONMENTS_ENVIRONMENT_ID_ASSETS_ASSET_ID_CONNECTIONS_CONNECTION_ID: ApiV1OrganizationsOrganizationIdEnvironmentsEnvironmentIdAssetsAssetIdConnectionsConnectionId,
        PathValues.API_V1_ORGANIZATIONS_ORGANIZATION_ID_OPERATIONS_OPERATION_ID: ApiV1OrganizationsOrganizationIdOperationsOperationId,
        PathValues.API_V1_OPERATIONS_OPERATION_ID: ApiV1OperationsOperationId,
        PathValues.API_V1_ORGANIZATIONS_ORGANIZATION_ID: ApiV1OrganizationsOrganizationId,
        PathValues.API_V1_ORGANIZATIONS_: ApiV1Organizations,
        PathValues.API_V1_ORGANIZATIONS_ORGANIZATION_ID_OPERATIONS_: ApiV1OrganizationsOrganizationIdOperations,
        PathValues.API_V1_SYSTEM_HEALTH_CHECK: ApiV1SystemHealthCheck,
        PathValues.API_V1_DEBUG_USER_AUTH: ApiV1DebugUserAuth,
        PathValues.API_V1_DEBUG_USER_ROLE_MIDDLEWARE_CHECK: ApiV1DebugUserRoleMiddlewareCheck,
    }
)

path_to_api = PathToApi(
    {
        PathValues.API_V1_ORGANIZATIONS_ORGANIZATION_ID_ENVIRONMENTS_ENVIRONMENT_ID_ASSETS_ASSET_ID: ApiV1OrganizationsOrganizationIdEnvironmentsEnvironmentIdAssetsAssetId,
        PathValues.API_V1_ORGANIZATIONS_ORGANIZATION_ID_ENVIRONMENTS_ENVIRONMENT_ID_ASSETS: ApiV1OrganizationsOrganizationIdEnvironmentsEnvironmentIdAssets,
        PathValues.API_V1_ORGANIZATIONS_ORGANIZATION_ID_ENVIRONMENTS_ENVIRONMENT_ID_ASSETS_ASSET_ID_ACTION: ApiV1OrganizationsOrganizationIdEnvironmentsEnvironmentIdAssetsAssetIdAction,
        PathValues.API_V1_ORGANIZATIONS_ORGANIZATION_ID_ENVIRONMENTS_ENVIRONMENT_ID_ASSETS_ASSET_ID_ACTION_ACTION_ID: ApiV1OrganizationsOrganizationIdEnvironmentsEnvironmentIdAssetsAssetIdActionActionId,
        PathValues.API_V1_ORGANIZATIONS_ORGANIZATION_ID_ENVIRONMENTS_ENVIRONMENT_ID_ASSET_BUNDLES: ApiV1OrganizationsOrganizationIdEnvironmentsEnvironmentIdAssetBundles,
        PathValues.API_V1_ORGANIZATIONS_ORGANIZATION_ID_ENVIRONMENTS_ENVIRONMENT_ID_CONNECTIONS: ApiV1OrganizationsOrganizationIdEnvironmentsEnvironmentIdConnections,
        PathValues.API_V1_ORGANIZATIONS_ORGANIZATION_ID_ENVIRONMENTS_ENVIRONMENT_ID: ApiV1OrganizationsOrganizationIdEnvironmentsEnvironmentId,
        PathValues.API_V1_ORGANIZATIONS_ORGANIZATION_ID_ENVIRONMENTS: ApiV1OrganizationsOrganizationIdEnvironments,
        PathValues.API_V1_WORKER_HEALTHCHECK: ApiV1WorkerHealthCheck,
        PathValues.API_V1_ORGANIZATIONS_ORGANIZATION_ID_ENVIRONMENTS_ENVIRONMENT_ID_ASSETS_ASSET_ID_CONNECTIONS_: ApiV1OrganizationsOrganizationIdEnvironmentsEnvironmentIdAssetsAssetIdConnections,
        PathValues.API_V1_ORGANIZATIONS_ORGANIZATION_ID_ENVIRONMENTS_ENVIRONMENT_ID_ASSETS_ASSET_ID_CONNECTIONS_CONNECTION_ID: ApiV1OrganizationsOrganizationIdEnvironmentsEnvironmentIdAssetsAssetIdConnectionsConnectionId,
        PathValues.API_V1_ORGANIZATIONS_ORGANIZATION_ID_OPERATIONS_OPERATION_ID: ApiV1OrganizationsOrganizationIdOperationsOperationId,
        PathValues.API_V1_OPERATIONS_OPERATION_ID: ApiV1OperationsOperationId,
        PathValues.API_V1_ORGANIZATIONS_ORGANIZATION_ID: ApiV1OrganizationsOrganizationId,
        PathValues.API_V1_ORGANIZATIONS_: ApiV1Organizations,
        PathValues.API_V1_ORGANIZATIONS_ORGANIZATION_ID_OPERATIONS_: ApiV1OrganizationsOrganizationIdOperations,
        PathValues.API_V1_SYSTEM_HEALTH_CHECK: ApiV1SystemHealthCheck,
        PathValues.API_V1_DEBUG_USER_AUTH: ApiV1DebugUserAuth,
        PathValues.API_V1_DEBUG_USER_ROLE_MIDDLEWARE_CHECK: ApiV1DebugUserRoleMiddlewareCheck,
    }
)
