"""
    Cloud API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import cloud_api_client
from cloud_api_client.api.assets_api import AssetsApi  # noqa: E501


class TestAssetsApi(unittest.TestCase):
    """AssetsApi unit test stubs"""

    def setUp(self):
        self.api = AssetsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_asset_api_v1_organizations_organization_id_environments_environment_id_assets_post(self):
        """Test case for create_asset_api_v1_organizations_organization_id_environments_environment_id_assets_post

        Create Asset  # noqa: E501
        """
        pass

    def test_delete_asset_by_id_api_v1_organizations_organization_id_environments_environment_id_assets_asset_id_delete(self):
        """Test case for delete_asset_by_id_api_v1_organizations_organization_id_environments_environment_id_assets_asset_id_delete

        Delete Asset By Id  # noqa: E501
        """
        pass

    def test_get_asset_by_id_api_v1_organizations_organization_id_environments_environment_id_assets_asset_id_get(self):
        """Test case for get_asset_by_id_api_v1_organizations_organization_id_environments_environment_id_assets_asset_id_get

        Get Asset By Id  # noqa: E501
        """
        pass

    def test_update_asset_by_id_api_v1_organizations_organization_id_environments_environment_id_assets_asset_id_put(self):
        """Test case for update_asset_by_id_api_v1_organizations_organization_id_environments_environment_id_assets_asset_id_put

        Update Asset By Id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
