"""
    Cloud API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cloud_api_client
from cloud_api_client.model.data import Data
from cloud_api_client.model.operation_status import OperationStatus
globals()['Data'] = Data
globals()['OperationStatus'] = OperationStatus
from cloud_api_client.model.operation_update import OperationUpdate


class TestOperationUpdate(unittest.TestCase):
    """OperationUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOperationUpdate(self):
        """Test OperationUpdate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OperationUpdate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
