"""
    Cloud API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import cloud_api_client
from cloud_api_client.api.environments_api import EnvironmentsApi  # noqa: E501


class TestEnvironmentsApi(unittest.TestCase):
    """EnvironmentsApi unit test stubs"""

    def setUp(self):
        self.api = EnvironmentsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_environment_api_v1_organizations_organization_id_environments_post(self):
        """Test case for create_environment_api_v1_organizations_organization_id_environments_post

        Create Environment  # noqa: E501
        """
        pass

    def test_delete_environment_by_id_api_v1_organizations_organization_id_environments_environment_id_delete(self):
        """Test case for delete_environment_by_id_api_v1_organizations_organization_id_environments_environment_id_delete

        Delete Environment By Id  # noqa: E501
        """
        pass

    def test_get_environment_allowed_assets_api_v1_organizations_organization_id_environments_environment_id_asset_bundles_get(self):
        """Test case for get_environment_allowed_assets_api_v1_organizations_organization_id_environments_environment_id_asset_bundles_get

        Get Environment Allowed Assets  # noqa: E501
        """
        pass

    def test_get_environment_by_id_api_v1_organizations_organization_id_environments_environment_id_get(self):
        """Test case for get_environment_by_id_api_v1_organizations_organization_id_environments_environment_id_get

        Get Environment By Id  # noqa: E501
        """
        pass

    def test_get_environment_connections_api_v1_organizations_organization_id_environments_environment_id_connections_get(self):
        """Test case for get_environment_connections_api_v1_organizations_organization_id_environments_environment_id_connections_get

        Get Environment Connections  # noqa: E501
        """
        pass

    def test_get_environments_api_v1_organizations_organization_id_environments_get(self):
        """Test case for get_environments_api_v1_organizations_organization_id_environments_get

        Get Environments  # noqa: E501
        """
        pass

    def test_update_environment_api_v1_organizations_organization_id_environments_environment_id_put(self):
        """Test case for update_environment_api_v1_organizations_organization_id_environments_environment_id_put

        Update Environment  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
