"""
    Cloud API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cloud_api_client
from cloud_api_client.model.structure import Structure


class TestStructure(unittest.TestCase):
    """Structure unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStructure(self):
        """Test Structure"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Structure()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
