# coding: utf-8

"""
    Cloud API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from cloud_api_client import schemas  # noqa: F401


class AssetStatus(
    schemas.EnumBase,
    schemas.StrSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    An enumeration.
    """
    
    @schemas.classproperty
    def FAILED(cls):
        return cls("FAILED")
    
    @schemas.classproperty
    def PENDING(cls):
        return cls("PENDING")
    
    @schemas.classproperty
    def REQUESTED(cls):
        return cls("REQUESTED")
    
    @schemas.classproperty
    def DEPLOYING(cls):
        return cls("DEPLOYING")
    
    @schemas.classproperty
    def DEPLOYED(cls):
        return cls("DEPLOYED")
    
    @schemas.classproperty
    def DESTROYED(cls):
        return cls("DESTROYED")
    
    @schemas.classproperty
    def DESTROYING(cls):
        return cls("DESTROYING")
