=begin
#Cloud API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.1.0-SNAPSHOT

=end

require 'cgi'

module CloudApiClient
  class UtilitiesApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Get Ping
    # @param [Hash] opts the optional parameters
    # @return [TextResponse]
    def get_ping_api_v1_debug_ping_get(opts = {})
      data, _status_code, _headers = get_ping_api_v1_debug_ping_get_with_http_info(opts)
      data
    end

    # Get Ping
    # @param [Hash] opts the optional parameters
    # @return [Array<(TextResponse, Integer, Hash)>] TextResponse data, response status code and response headers
    def get_ping_api_v1_debug_ping_get_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: UtilitiesApi.get_ping_api_v1_debug_ping_get ...'
      end
      # resource path
      local_var_path = '/api/v1/debug/ping'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'TextResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :"UtilitiesApi.get_ping_api_v1_debug_ping_get",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: UtilitiesApi#get_ping_api_v1_debug_ping_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Get User
    # @param [Hash] opts the optional parameters
    # @return [Object]
    def get_user_api_v1_debug_user_auth_get(opts = {})
      data, _status_code, _headers = get_user_api_v1_debug_user_auth_get_with_http_info(opts)
      data
    end

    # Get User
    # @param [Hash] opts the optional parameters
    # @return [Array<(Object, Integer, Hash)>] Object data, response status code and response headers
    def get_user_api_v1_debug_user_auth_get_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: UtilitiesApi.get_user_api_v1_debug_user_auth_get ...'
      end
      # resource path
      local_var_path = '/api/v1/debug/user_auth'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Object'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['HTTPBearer']

      new_options = opts.merge(
        :operation => :"UtilitiesApi.get_user_api_v1_debug_user_auth_get",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: UtilitiesApi#get_user_api_v1_debug_user_auth_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Get User Role
    # @param organization_id [String] 
    # @param [Hash] opts the optional parameters
    # @return [Object]
    def get_user_role_api_v1_debug_user_role_middleware_check_get(organization_id, opts = {})
      data, _status_code, _headers = get_user_role_api_v1_debug_user_role_middleware_check_get_with_http_info(organization_id, opts)
      data
    end

    # Get User Role
    # @param organization_id [String] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(Object, Integer, Hash)>] Object data, response status code and response headers
    def get_user_role_api_v1_debug_user_role_middleware_check_get_with_http_info(organization_id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: UtilitiesApi.get_user_role_api_v1_debug_user_role_middleware_check_get ...'
      end
      # verify the required parameter 'organization_id' is set
      if @api_client.config.client_side_validation && organization_id.nil?
        fail ArgumentError, "Missing the required parameter 'organization_id' when calling UtilitiesApi.get_user_role_api_v1_debug_user_role_middleware_check_get"
      end
      # resource path
      local_var_path = '/api/v1/debug/user_role_middleware_check'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'organization_id'] = organization_id

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Object'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['HTTPBearer']

      new_options = opts.merge(
        :operation => :"UtilitiesApi.get_user_role_api_v1_debug_user_role_middleware_check_get",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: UtilitiesApi#get_user_role_api_v1_debug_user_role_middleware_check_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
