# coding: utf-8

"""
    Cloud API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

from cloud_api_client.paths.api_v1_organizations_organization_id_environments_environment_id_assets_asset_id_action.post import ActionCreate
from cloud_api_client.paths.api_v1_organizations_organization_id_environments_environment_id_assets_asset_id_action_action_id.get import ActionGet


class ActionsApi(
    ActionCreate,
    ActionGet,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
