# coding: utf-8

"""
    Cloud API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

from cloud_api_client.paths.api_v1_organizations_organization_id_environments_environment_id_assets_asset_id_connections_.post import ConnectionCreate
from cloud_api_client.paths.api_v1_organizations_organization_id_environments_environment_id_assets_asset_id_connections_connection_id.delete import ConnectionDelete
from cloud_api_client.paths.api_v1_organizations_organization_id_environments_environment_id_assets_asset_id_connections_connection_id.get import ConnectionGet


class ConnectionsApi(
    ConnectionCreate,
    ConnectionDelete,
    ConnectionGet,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
