# coding: utf-8

"""
    Cloud API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

from cloud_api_client.paths.api_v1_debug_user_auth.get import GetUser
from cloud_api_client.paths.api_v1_debug_user_role_middleware_check.get import GetUserRole


class UtilitiesApi(
    GetUser,
    GetUserRole,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
