name: Generate clients

on:
  workflow_dispatch:

jobs:
  generate:
    name: Generate Clients
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: add ssh key for use in deps installation
        run: |
          # this link below looks like it will mostly impact executioner, but that is a dep of cloud-api via client
          # needed for libcurl - https://github.com/aptible/executioner-clients/runs/7506231404?check_suite_focus=true
          #  FileNotFoundError: [Errno 2] No such file or directory: 'curl-config'
          sudo apt-get update && sudo apt-get install -yq libcurl4-openssl-dev libssl-dev
          mkdir -p ~/.ssh && \
            ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

        # ssh key is for building
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.APTIBLE_ROBOT_PRIVATE_SSH_KEY }}

      # 1- Install dependencies to setup the repo
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -e .[dev]

      - name: generate openapi.json for reuse
        run: |
          source ./scripts/setenvs.sh
          python -m scripts.openapi.generate openapi.json

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      # 2 - Generate the separate clients!
      - run: ./scripts/generate-clients-gha.sh
        env:
          # Needed to open pull request
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USERNAME: "aptible-robot"
          # WARNING - sometimes below is also spelled WRITABLE
          # ALSO WARNING - move this to `with` section if in an action!
          DEPLOY_KEY: ${{ secrets.WRITEABLE_DEPLOY_KEY }}