name: Python Client Test

on:
  push:

jobs:
  python-client-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r test-requirements.txt
        working-directory: ./clients/python

      - name: Run tests
        run: python -m pytest
        working-directory: ./clients/python
