name: Ruby Client Test

on:
  push:

jobs:
  ruby-client-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: Install dependencies
        run: bundle install
        working-directory: ./clients/ruby
      - name: Run tests
        run: bundle exec rake
        working-directory: ./clients/ruby